name: ➕ New pattern/path
description: Add a new path or pattern to this repoistry
labels: ["new pattern/path"]

body:
  - type: markdown
    attributes:
      value: |
      
        This is the repoistry where Natro Macro stores and fetches patterns and paths confirmed to be safe by the developers. If you want to add a pattern or path to the list of safe imports, you are in the right place.
        
        The title of this issue should be name of your pattern. You do not need to upload your pattern, it will be created based on the information you give in this issue.

  - type: checkboxes
    attributes:
      label: By adding your pattern to this repoistry, you agree to liscense your pattern under [GNU GPL v3.0](blob/main/LICENSE)
      options:
        - label: I agree
          required: true
    validations:
      required: true

  - type: textarea
    id: pattern
    attributes:
      label: "Paste in your pattern/path's code here"
      placeholder: |
          "nm_Walk(5, "FwdKey")"
          "Sleep(1000)"
          "..."
      render: ahk
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: What is the name you want this pattern to be credited under?
      description: People usually use their Discord or Roblox username. 
    validations:
      required: true
